; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nucleo_f103rb
src_dir = src

[env:nucleo_f103rb]
platform = ststm32
board = nucleo_f103rb
framework = arduino
monitor_speed = 115200
upload_protocol = stlink
build_src_filter =
  +<*>
  -<include/>
  -<include/**>
build_flags =
  -Isrc/include/block-ciphers/include
  -Isrc/include/libtomcrypt/src/headers
  ; Toggle per-algorithm benchmarks.
  ; STM32F103RB has substantially more room than UNO.
  ; Set to 1 to include, 0 to exclude.
  -DENABLE_TINYAES_EXP=1
  -DENABLE_TEA_EXP=1
  -DENABLE_SIMECK_EXP=1
  -DENABLE_SIMON_EXP=1
  -DENABLE_SPECK_EXP=1
  -DENABLE_LEA_EXP=1
  -DENABLE_HIGHT_EXP=1
  -DENABLE_SEED_EXP=1
  -DENABLE_RC5_EXP=1
  -DENABLE_TWOFISH_EXP=1
lib_deps = rweather/Crypto@^0.4.0
